package com.open.studyos.db.autocode;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "book_table".
 */
public class BookInfo {

    private String bookId;
    private String bookName;
    private String userId;

    // KEEP FIELDS - put your custom fields here
	private String hecphecp;
    // KEEP FIELDS END

    public BookInfo() {
    }

    public BookInfo(String bookId) {
        this.bookId = bookId;
    }

    public BookInfo(String bookId, String bookName, String userId) {
        this.bookId = bookId;
        this.bookName = bookName;
        this.userId = userId;
    }

    public String getBookId() {
        return bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    // KEEP METHODS - put your custom methods here
	public void sethecp(){
	   hecphecp="123";
	}
    // KEEP METHODS END

}
