package com.open.studyos.db.autocode;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.open.studyos.db.autocode.UserInfo;
import com.open.studyos.db.autocode.BookInfo;

import com.open.studyos.db.autocode.UserInfoDao;
import com.open.studyos.db.autocode.BookInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig bookInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final BookInfoDao bookInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(BookInfo.class, bookInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        bookInfoDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

}
